In [1]:
import pandas as pd

In [3]:
df_path = '/Users/phr/Desktop/BigTeam/big_final/data/3대중증 사망자.csv'
df = pd.read_csv(df_path, encoding='cp949')

In [4]:
df

              시군구별 순환계통 사망자수 운수사고 사망자수 낙상(추락) 사망자수 사망자수 합계
0            00 전국    62,370     3,624       2,722  68,716
1         11 서울특별시     9,350       367         423  10,140
2     　　　11010 종로구       229         7          11     247
3      　　　11020 중구       194         4          10     208
4     　　　11030 용산구       247         5          14     266
..             ...       ...       ...         ...     ...
297         39 제주도       760        52          29     841
298   　　　39010 제주시       551        32          18     601
299  　　　39020 서귀포시       209        20          11     240
300  　　　39310 북제주군       NaN       NaN         NaN       0
301  　　　39320 남제주군       NaN       NaN         NaN       0

[302 rows x 5 columns]

In [5]:
before_list = list(df['시군구별'])

In [6]:
len(before_list)

302

In [7]:
before_list

['00 전국',
 '11 서울특별시',
 '\u3000\u3000\u300011010 종로구',
 '\u3000\u3000\u300011020 중구',
 '\u3000\u3000\u300011030 용산구',
 '\u3000\u3000\u300011040 성동구',
 '\u3000\u3000\u300011050 광진구',
 '\u3000\u3000\u300011060 동대문구',
 '\u3000\u3000\u300011070 중랑구',
 '\u3000\u3000\u300011080 성북구',
 '\u3000\u3000\u300011090 강북구',
 '\u3000\u3000\u300011100 도봉구',
 '\u3000\u3000\u300011110 노원구',
 '\u3000\u3000\u300011120 은평구',
 '\u3000\u3000\u300011130 서대문구',
 '\u3000\u3000\u300011140 마포구',
 '\u3000\u3000\u300011150 양천구',
 '\u3000\u3000\u300011160 강서구',
 '\u3000\u3000\u300011170 구로구',
 '\u3000\u3000\u300011180 금천구',
 '\u3000\u3000\u300011190 영등포구',
 '\u3000\u3000\u300011200 동작구',
 '\u3000\u3000\u300011210 관악구',
 '\u3000\u3000\u300011220 서초구',
 '\u3000\u3000\u300011230 강남구',
 '\u3000\u3000\u300011240 송파구',
 '\u3000\u3000\u300011250 강동구',
 '21 부산광역시',
 '\u3000\u3000\u300021010 중구',
 '\u3000\u3000\u300021020 서구',
 '\u3000\u3000\u300021030 동구',
 '\u3000\u3000\u300021040 영도구',
 '\u3000\u3000\u300021050 부산진구',
 '\u3000\u3000\u300021060 동래구',
 '\u3000\u3000\u300021070 남구',
 '\u3000\u3000\u300021080 북구',
 '\u3000\u3000\u300021090 해운대구',
 '\u3000\u3000\u300021100 사하구',
 '\u3000\u3000\u300021110 금정구',
 '\u3000\u3000\u300021120 강서구',
 '\u3000\u3000\u300021130 연제구',
 '\u3000\u3000\u300021140 수영구',
 '\u3000\u3000\u300021150 사상구',
 '\u3000\u3000\u300021310 기장군',
 '22 대구광역시',
 '\u3000\u3000\u300022010 중구',
 '\u3000\u3000\u300022020 동구',
 '\u3000\u3000\u300022030 서구',
 '\u3000\u3000\u300022040 남구',
 '\u3000\u3000\u300022050 북구',
 '\u3000\u3000\u300022060 수성구',
 '\u3000\u3000\u300022070 달서구',
 '\u3000\u3000\u300022310 달성군',
 '23 인천광역시',
 '\u3000\u3000\u300023010 중구',
 '\u3000\u3000\u300023020 동구',
 '\u3000\u3000\u300023030 남구',
 '\u3000\u3000\u300023040 연수구',
 '\u3000\u3000\u300023050 남동구',
 '\u3000\u3000\u300023060 부평구',
 '\u3000\u3000\u300023070 계양구',
 '\u3000\u3000\u300023080 서구',
 '\u3000\u3000\u300023090 미추홀구',
 '\u3000\u3000\u300023310 강화군',
 '\u3000\u3000\u300023320 옹진군',
 '24 광주광역시',
 '\u3000\u3000\u300024010 동구',
 '\u3000\u3000\u300024020 서구',
 '\u3000\u3000\u300024030 남구',
 '\u3000\u3000\u300024040 북구',
 '\u3000\u3000\u300024050 광산구',
 '25 대전광역시',
 '\u3000\u3000\u300025010 동구',
 '\u3000\u3000\u300025020 중구',
 '\u3000\u3000\u300025030 서구',
 '\u3000\u3000\u300025040 유성구',
 '\u3000\u3000\u300025050 대덕구',
 '26 울산광역시',
 '\u3000\u3000\u300026010 중구',
 '\u3000\u3000\u300026020 남구',
 '\u3000\u3000\u300026030 동구',
 '\u3000\u3000\u300026040 북구',
 '\u3000\u3000\u300026310 울주군',
 '29 세종특별자치시',
 '\u3000\u3000\u300029010 세종시',
 '31 경기도',
 '\u3000\u3000\u300031010 수원시',
 '\u3000\u3000\u300031011 장안구',
 '\u3000\u3000\u300031012 권선구',
 '\u3000\u3000\u300031013 팔달구',
 '\u3000\u3000\u300031014 영통구',
 '\u3000\u3000\u300031020 성남시',
 '\u3000\u3000\u300031021 수정구',
 '\u3000\u3000\u300031022 중원구',
 '\u3000\u3000\u300031023 분당구',
 '\u3000\u3000\u300031030 의정부시',
 '\u3000\u3000\u300031040 안양시',
 '\u3000\u3000\u300031041 만안구',
 '\u3000\u3000\u300031042 동안구',
 '\u3000\u3000\u300031050 부천시',
 '\u3000\u3000\u300031051 원미구',
 '\u3000\u3000\u300031052 소사구',
 '\u3000\u3000\u300031053 오정구',
 '\u3000\u3000\u300031060 광명시',
 '\u3000\u3000\u300031070 평택시',
 '\u3000\u3000\u300031080 동두천시',
 '\u3000\u3000\u300031090 안산시',
 '\u3000\u3000\u300031091 상록구',
 '\u3000\u3000\u300031092 단원구',
 '\u3000\u3000\u300031100 고양시',
 '\u3000\u3000\u300031101 덕양구',
 '\u3000\u3000\u300031102 일산구',
 '\u3000\u3000\u300031103 일산동구',
 '\u3000\u3000\u300031104 일산서구',
 '\u3000\u3000\u300031110 과천시',
 '\u3000\u3000\u300031120 구리시',
 '\u3000\u3000\u300031130 남양주시',
 '\u3000\u3000\u300031140 오산시',
 '\u3000\u3000\u300031150 시흥시',
 '\u3000\u3000\u300031160 군포시',
 '\u3000\u3000\u300031170 의왕시',
 '\u3000\u3000\u300031180 하남시',
 '\u3000\u3000\u300031190 용인시',
 '\u3000\u3000\u300031191 처인구',
 '\u3000\u3000\u300031192 기흥구',
 '\u3000\u3000\u300031193 수지구',
 '\u3000\u3000\u300031200 파주시',
 '\u3000\u3000\u300031210 이천시',
 '\u3000\u3000\u300031220 안성시',
 '\u3000\u3000\u300031230 김포시',
 '\u3000\u3000\u300031240 화성시',
 '\u3000\u3000\u300031250 광주시',
 '\u3000\u3000\u300031260 양주시',
 '\u3000\u3000\u300031270 포천시',
 '\u3000\u3000\u300031280 여주시',
 '\u3000\u3000\u300031310 양주군',
 '\u3000\u3000\u300031320 여주군',
 '\u3000\u3000\u300031330 화성군',
 '\u3000\u3000\u300031340 광주군',
 '\u3000\u3000\u300031350 연천군',
 '\u3000\u3000\u300031360 포천군',
 '\u3000\u3000\u300031370 가평군',
 '\u3000\u3000\u300031380 양평군',
 '32 강원도',
 '\u3000\u3000\u300032010 춘천시',
 '\u3000\u3000\u300032020 원주시',
 '\u3000\u3000\u300032030 강릉시',
 '\u3000\u3000\u300032040 동해시',
 '\u3000\u3000\u300032050 태백시',
 '\u3000\u3000\u300032060 속초시',
 '\u3000\u3000\u300032070 삼척시',
 '\u3000\u3000\u300032310 홍천군',
 '\u3000\u3000\u300032320 횡성군',
 '\u3000\u3000\u300032330 영월군',
 '\u3000\u3000\u300032340 평창군',
 '\u3000\u3000\u300032350 정선군',
 '\u3000\u3000\u300032360 철원군',
 '\u3000\u3000\u300032370 화천군',
 '\u3000\u3000\u300032380 양구군',
 '\u3000\u3000\u300032390 인제군',
 '\u3000\u3000\u300032400 고성군',
 '\u3000\u3000\u300032410 양양군',
 '33 충청북도',
 '\u3000\u3000\u300033010 청주시',
 '\u3000\u3000\u300033011 상당구',
 '\u3000\u3000\u300033012 흥덕구',
 '\u3000\u3000\u300033020 충주시',
 '\u3000\u3000\u300033030 제천시',
 '\u3000\u3000\u300033040 청주시',
 '\u3000\u3000\u300033041 상당구',
 '\u3000\u3000\u300033042 서원구',
 '\u3000\u3000\u300033043 흥덕구',
 '\u3000\u3000\u300033044 청원구',
 '\u3000\u3000\u300033310 청원군',
 '\u3000\u3000\u300033320 보은군',
 '\u3000\u3000\u300033330 옥천군',
 '\u3000\u3000\u300033340 영동군',
 '\u3000\u3000\u300033350 진천군',
 '\u3000\u3000\u300033360 괴산군',
 '\u3000\u3000\u300033370 음성군',
 '\u3000\u3000\u300033380 단양군',
 '\u3000\u3000\u300033390 증평군',
 '34 충청남도',
 '\u3000\u3000\u300034010 천안시',
 '\u3000\u3000\u300034011 동남구',
 '\u3000\u3000\u300034012 서북구',
 '\u3000\u3000\u300034020 공주시',
 '\u3000\u3000\u300034030 보령시',
 '\u3000\u3000\u300034040 아산시',
 '\u3000\u3000\u300034050 서산시',
 '\u3000\u3000\u300034060 논산시',
 '\u3000\u3000\u300034070 계룡시',
 '\u3000\u3000\u300034080 당진시',
 '\u3000\u3000\u300034310 금산군',
 '\u3000\u3000\u300034320 연기군',
 '\u3000\u3000\u300034330 부여군',
 '\u3000\u3000\u300034340 서천군',
 '\u3000\u3000\u300034350 청양군',
 '\u3000\u3000\u300034360 홍성군',
 '\u3000\u3000\u300034370 예산군',
 '\u3000\u3000\u300034380 태안군',
 '\u3000\u3000\u300034390 당진군',
 '35 전라북도',
 '\u3000\u3000\u300035010 전주시',
 '\u3000\u3000\u300035011 완산구',
 '\u3000\u3000\u300035012 덕진구',
 '\u3000\u3000\u300035020 군산시',
 '\u3000\u3000\u300035030 익산시',
 '\u3000\u3000\u300035040 정읍시',
 '\u3000\u3000\u300035050 남원시',
 '\u3000\u3000\u300035060 김제시',
 '\u3000\u3000\u300035310 완주군',
 '\u3000\u3000\u300035320 진안군',
 '\u3000\u3000\u300035330 무주군',
 '\u3000\u3000\u300035340 장수군',
 '\u3000\u3000\u300035350 임실군',
 '\u3000\u3000\u300035360 순창군',
 '\u3000\u3000\u300035370 고창군',
 '\u3000\u3000\u300035380 부안군',
 '36 전라남도',
 '\u3000\u3000\u300036010 목포시',
 '\u3000\u3000\u300036020 여수시',
 '\u3000\u3000\u300036030 순천시',
 '\u3000\u3000\u300036040 나주시',
 '\u3000\u3000\u300036060 광양시',
 '\u3000\u3000\u300036310 담양군',
 '\u3000\u3000\u300036320 곡성군',
 '\u3000\u3000\u300036330 구례군',
 '\u3000\u3000\u300036350 고흥군',
 '\u3000\u3000\u300036360 보성군',
 '\u3000\u3000\u300036370 화순군',
 '\u3000\u3000\u300036380 장흥군',
 '\u3000\u3000\u300036390 강진군',
 '\u3000\u3000\u300036400 해남군',
 '\u3000\u3000\u300036410 영암군',
 '\u3000\u3000\u300036420 무안군',
 '\u3000\u3000\u300036430 함평군',
 '\u3000\u3000\u300036440 영광군',
 '\u3000\u3000\u300036450 장성군',
 '\u3000\u3000\u300036460 완도군',
 '\u3000\u3000\u300036470 진도군',
 '\u3000\u3000\u300036480 신안군',
 '37 경상북도',
 '\u3000\u3000\u300037010 포항시',
 '\u3000\u3000\u300037011 남구',
 '\u3000\u3000\u300037012 북구',
 '\u3000\u3000\u300037020 경주시',
 '\u3000\u3000\u300037030 김천시',
 '\u3000\u3000\u300037040 안동시',
 '\u3000\u3000\u300037050 구미시',
 '\u3000\u3000\u300037060 영주시',
 '\u3000\u3000\u300037070 영천시',
 '\u3000\u3000\u300037080 상주시',
 '\u3000\u3000\u300037090 문경시',
 '\u3000\u3000\u300037100 경산시',
 '\u3000\u3000\u300037310 군위군',
 '\u3000\u3000\u300037320 의성군',
 '\u3000\u3000\u300037330 청송군',
 '\u3000\u3000\u300037340 영양군',
 '\u3000\u3000\u300037350 영덕군',
 '\u3000\u3000\u300037360 청도군',
 '\u3000\u3000\u300037370 고령군',
 '\u3000\u3000\u300037380 성주군',
 '\u3000\u3000\u300037390 칠곡군',
 '\u3000\u3000\u300037400 예천군',
 '\u3000\u3000\u300037410 봉화군',
 '\u3000\u3000\u300037420 울진군',
 '\u3000\u3000\u300037430 울릉군',
 '38 경상남도',
 '\u3000\u3000\u300038010 창원시',
 '\u3000\u3000\u300038020 마산시',
 '\u3000\u3000\u300038021 합포구',
 '\u3000\u3000\u300038022 회원구',
 '\u3000\u3000\u300038030 진주시',
 '\u3000\u3000\u300038040 진해시',
 '\u3000\u3000\u300038050 통영시',
 '\u3000\u3000\u300038060 사천시',
 '\u3000\u3000\u300038110 통합창원시',
 '\u3000\u3000\u300038111 의창구',
 '\u3000\u3000\u300038112 성산구',
 '\u3000\u3000\u300038113 마산합포구',
 '\u3000\u3000\u300038114 마산회원구',
 '\u3000\u3000\u300038115 진해구',
 '\u3000\u3000\u300038070 김해시',
 '\u3000\u3000\u300038080 밀양시',
 '\u3000\u3000\u300038090 거제시',
 '\u3000\u3000\u300038100 양산시',
 '\u3000\u3000\u300038310 의령군',
 '\u3000\u3000\u300038320 함안군',
 '\u3000\u3000\u300038330 창녕군',
 '\u3000\u3000\u300038340 고성군',
 '\u3000\u3000\u300038350 남해군',
 '\u3000\u3000\u300038360 하동군',
 '\u3000\u3000\u300038370 산청군',
 '\u3000\u3000\u300038380 함양군',
 '\u3000\u3000\u300038390 거창군',
 '\u3000\u3000\u300038400 합천군',
 '39 제주도',
 '\u3000\u3000\u300039010 제주시',
 '\u3000\u3000\u300039020 서귀포시',
 '\u3000\u3000\u300039310 북제주군',
 '\u3000\u3000\u300039320 남제주군']

In [8]:
raw_sig = []

In [15]:
a = before_list[3].split()

In [17]:
a[0]

'11020'

In [20]:
for i in before_list:
    data = i.split()
    data = int(data[0])
    raw_sig.append(data)

In [21]:
raw_sig

[0,
 11,
 11010,
 11020,
 11030,
 11040,
 11050,
 11060,
 11070,
 11080,
 11090,
 11100,
 11110,
 11120,
 11130,
 11140,
 11150,
 11160,
 11170,
 11180,
 11190,
 11200,
 11210,
 11220,
 11230,
 11240,
 11250,
 21,
 21010,
 21020,
 21030,
 21040,
 21050,
 21060,
 21070,
 21080,
 21090,
 21100,
 21110,
 21120,
 21130,
 21140,
 21150,
 21310,
 22,
 22010,
 22020,
 22030,
 22040,
 22050,
 22060,
 22070,
 22310,
 23,
 23010,
 23020,
 23030,
 23040,
 23050,
 23060,
 23070,
 23080,
 23090,
 23310,
 23320,
 24,
 24010,
 24020,
 24030,
 24040,
 24050,
 25,
 25010,
 25020,
 25030,
 25040,
 25050,
 26,
 26010,
 26020,
 26030,
 26040,
 26310,
 29,
 29010,
 31,
 31010,
 31011,
 31012,
 31013,
 31014,
 31020,
 31021,
 31022,
 31023,
 31030,
 31040,
 31041,
 31042,
 31050,
 31051,
 31052,
 31053,
 31060,
 31070,
 31080,
 31090,
 31091,
 31092,
 31100,
 31101,
 31102,
 31103,
 31104,
 31110,
 31120,
 31130,
 31140,
 31150,
 31160,
 31170,
 31180,
 31190,
 31191,
 31192,
 31193,
 31200,
 31210,
 31220,
 31230,
 31240,
 31250,
 31260,
 31270,
 31280,
 31310,
 31320,
 31330,
 31340,
 31350,
 31360,
 31370,
 31380,
 32,
 32010,
 32020,
 32030,
 32040,
 32050,
 32060,
 32070,
 32310,
 32320,
 32330,
 32340,
 32350,
 32360,
 32370,
 32380,
 32390,
 32400,
 32410,
 33,
 33010,
 33011,
 33012,
 33020,
 33030,
 33040,
 33041,
 33042,
 33043,
 33044,
 33310,
 33320,
 33330,
 33340,
 33350,
 33360,
 33370,
 33380,
 33390,
 34,
 34010,
 34011,
 34012,
 34020,
 34030,
 34040,
 34050,
 34060,
 34070,
 34080,
 34310,
 34320,
 34330,
 34340,
 34350,
 34360,
 34370,
 34380,
 34390,
 35,
 35010,
 35011,
 35012,
 35020,
 35030,
 35040,
 35050,
 35060,
 35310,
 35320,
 35330,
 35340,
 35350,
 35360,
 35370,
 35380,
 36,
 36010,
 36020,
 36030,
 36040,
 36060,
 36310,
 36320,
 36330,
 36350,
 36360,
 36370,
 36380,
 36390,
 36400,
 36410,
 36420,
 36430,
 36440,
 36450,
 36460,
 36470,
 36480,
 37,
 37010,
 37011,
 37012,
 37020,
 37030,
 37040,
 37050,
 37060,
 37070,
 37080,
 37090,
 37100,
 37310,
 37320,
 37330,
 37340,
 37350,
 37360,
 37370,
 37380,
 37390,
 37400,
 37410,
 37420,
 37430,
 38,
 38010,
 38020,
 38021,
 38022,
 38030,
 38040,
 38050,
 38060,
 38110,
 38111,
 38112,
 38113,
 38114,
 38115,
 38070,
 38080,
 38090,
 38100,
 38310,
 38320,
 38330,
 38340,
 38350,
 38360,
 38370,
 38380,
 38390,
 38400,
 39,
 39010,
 39020,
 39310,
 39320]

In [22]:
sig = {"sig_cd":raw_sig}

In [23]:
df = df.assign(**sig)

In [24]:
df

              시군구별 순환계통 사망자수 운수사고 사망자수 낙상(추락) 사망자수 사망자수 합계  sig_cd
0            00 전국    62,370     3,624       2,722  68,716       0
1         11 서울특별시     9,350       367         423  10,140      11
2     　　　11010 종로구       229         7          11     247   11010
3      　　　11020 중구       194         4          10     208   11020
4     　　　11030 용산구       247         5          14     266   11030
..             ...       ...       ...         ...     ...     ...
297         39 제주도       760        52          29     841      39
298   　　　39010 제주시       551        32          18     601   39010
299  　　　39020 서귀포시       209        20          11     240   39020
300  　　　39310 북제주군       NaN       NaN         NaN       0   39310
301  　　　39320 남제주군       NaN       NaN         NaN       0   39320

[302 rows x 6 columns]

In [25]:
df.to_csv('./3대사망자.csv')

In [3]:

df = pd.read_csv('emci_final_list.csv', encoding='utf-8')

In [4]:
df

,Unnamed: 0,행정구역,sig_cd,진짜 구급차 출동시간 표준화,기대수명 표준화,병원수 표준화,보건시설 표준화,구급차 표준화,의사수 표준화,지방소멸지수 표준화,지역별중증사망수치,정규화사망수치,emci
0,0,전라남도 진도군,46900,6.893050,0.000000,0.5,0.0,1.846154,0.437811,1.791210,328.0,0.632979,11.468225
1,1,경상남도 합천군,48890,5.709260,3.000000,0.0,0.0,3.076923,0.477612,0.198816,450.0,NaN,12.462611
2,2,경상남도 고성군,48820,6.826077,2.038462,0.5,0.0,1.846154,0.318408,1.521162,381.0,0.460106,13.050262
3,3,경상남도 의령군,48720,6.857969,4.115385,0.0,0.0,1.230769,0.199005,0.662017,124.4,0.228723,13.065145
4,4,강원도 철원군,42780,5.042618,0.115385,0.0,0.0,1.846154,0.238806,5.926777,242.3,0.564072,13.169740
...,...,...,...,...,...,...,...,...,...,...,...,...,...
177,177,서울특별시 서초구,11650,8.000000,24.000000,6.5,0.0,1.230769,2.666667,20.550177,70.5,0.979449,62.947613
178,178,대전광역시 유성구,30200,7.898045,14.769231,7.0,0.0,3.076923,0.597015,30.401035,62.0,1.000000,63.742249
179,179,경기도 화성시,41590,4.056160,13.000000,8.0,0.0,8.000000,0.358209,32.000000,75.9,0.966393,65.414369
180,180,서울특별시 송파구,11710,8.000000,19.769231,11.5,0.0,4.307692,1.791045,22.197424,77.5,0.962524,67.565391
181,181,서울특별시 강남구,11680,8.000000,22.961538,18.0,0.0,4.923077,4.815920,21.300222,70.9,0.978482,80.000758

In [6]:
df.iloc[1,11] = 0.594872

In [12]:
df.iloc[0,4] = 0.403846154

In [13]:
df.head(10)

,Unnamed: 0,행정구역,sig_cd,진짜 구급차 출동시간 표준화,기대수명 표준화,병원수 표준화,보건시설 표준화,구급차 표준화,의사수 표준화,지방소멸지수 표준화,지역별중증사망수치,정규화사망수치,emci
0,0,전라남도 진도군,46900,6.893050,0.403846,0.5,0.0,1.846154,0.437811,1.791210,328.0,0.632979,11.468225
1,1,경상남도 합천군,48890,5.709260,3.000000,0.0,0.0,3.076923,0.477612,0.198816,450.0,0.594872,12.462611
2,2,경상남도 고성군,48820,6.826077,2.038462,0.5,0.0,1.846154,0.318408,1.521162,381.0,0.460106,13.050262
3,3,경상남도 의령군,48720,6.857969,4.115385,0.0,0.0,1.230769,0.199005,0.662017,124.4,0.228723,13.065145
4,4,강원도 철원군,42780,5.042618,0.115385,0.0,0.0,1.846154,0.238806,5.926777,242.3,0.564072,13.169740
5,5,경상북도 청도군,47820,6.509051,4.346154,0.5,0.0,1.230769,0.477612,0.460262,475.6,0.723888,13.523847
6,6,경상남도 남해군,48840,6.114388,5.115385,0.0,0.0,1.846154,0.278607,0.488178,403.3,0.061896,13.842711
7,7,경상남도 창녕군,48740,6.740168,2.307692,0.5,0.0,2.461538,0.477612,1.551458,353.0,0.137331,14.038468
8,8,충청북도 괴산군,43760,6.231889,3.461538,0.5,0.0,3.076923,0.318408,0.664523,285.5,0.459623,14.253282
9,9,경상북도 성주군,47840,6.926835,4.730769,0.0,0.0,1.230769,0.398010,1.399913,372.9,0.147485,14.686297

In [9]:
df.tail(10)

,Unnamed: 0,행정구역,sig_cd,진짜 구급차 출동시간 표준화,기대수명 표준화,병원수 표준화,보건시설 표준화,구급차 표준화,의사수 표준화,지방소멸지수 표준화,지역별중증사망수치,정규화사망수치,emci
172,172,서울특별시 관악구,11620,8.000000,14.807692,5.5,0.0,3.692308,0.477612,27.489988,119.4,0.861219,59.967600
173,173,서울특별시 마포구,11440,8.000000,17.269231,2.0,0.0,4.307692,0.756219,28.257480,90.6,0.930851,60.590622
174,174,서울특별시 영등포구,11560,8.000000,17.500000,7.5,0.0,3.692308,1.631841,24.060350,121.2,0.856867,62.384499
175,175,광주광역시 광산구,29200,7.751342,8.615385,12.0,0.0,5.538462,0.676617,28.166176,79.1,0.958656,62.747981
176,176,대구광역시 수성구,27290,7.995416,15.846154,20.0,0.0,3.076923,0.995025,15.017575,111.9,0.879352,62.931092
177,177,서울특별시 서초구,11650,8.000000,24.000000,6.5,0.0,1.230769,2.666667,20.550177,70.5,0.979449,62.947613
178,178,대전광역시 유성구,30200,7.898045,14.769231,7.0,0.0,3.076923,0.597015,30.401035,62.0,1.000000,63.742249
179,179,경기도 화성시,41590,4.056160,13.000000,8.0,0.0,8.000000,0.358209,32.000000,75.9,0.966393,65.414369
180,180,서울특별시 송파구,11710,8.000000,19.769231,11.5,0.0,4.307692,1.791045,22.197424,77.5,0.962524,67.565391
181,181,서울특별시 강남구,11680,8.000000,22.961538,18.0,0.0,4.923077,4.815920,21.300222,70.9,0.978482,80.000758

In [10]:
df_output = df.drop('지역별중증사망수치', axis=1)

In [11]:
df_output

,Unnamed: 0,행정구역,sig_cd,진짜 구급차 출동시간 표준화,기대수명 표준화,병원수 표준화,보건시설 표준화,구급차 표준화,의사수 표준화,지방소멸지수 표준화,정규화사망수치,emci
0,0,전라남도 진도군,46900,6.893050,0.000000,0.5,0.0,1.846154,0.437811,1.791210,0.632979,11.468225
1,1,경상남도 합천군,48890,5.709260,3.000000,0.0,0.0,3.076923,0.477612,0.198816,0.594872,12.462611
2,2,경상남도 고성군,48820,6.826077,2.038462,0.5,0.0,1.846154,0.318408,1.521162,0.460106,13.050262
3,3,경상남도 의령군,48720,6.857969,4.115385,0.0,0.0,1.230769,0.199005,0.662017,0.228723,13.065145
4,4,강원도 철원군,42780,5.042618,0.115385,0.0,0.0,1.846154,0.238806,5.926777,0.564072,13.169740
...,...,...,...,...,...,...,...,...,...,...,...,...
177,177,서울특별시 서초구,11650,8.000000,24.000000,6.5,0.0,1.230769,2.666667,20.550177,0.979449,62.947613
178,178,대전광역시 유성구,30200,7.898045,14.769231,7.0,0.0,3.076923,0.597015,30.401035,1.000000,63.742249
179,179,경기도 화성시,41590,4.056160,13.000000,8.0,0.0,8.000000,0.358209,32.000000,0.966393,65.414369
180,180,서울특별시 송파구,11710,8.000000,19.769231,11.5,0.0,4.307692,1.791045,22.197424,0.962524,67.565391
181,181,서울특별시 강남구,11680,8.000000,22.961538,18.0,0.0,4.923077,4.815920,21.300222,0.978482,80.000758